config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: [:registrations, :passwords], controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations'
      }
  root 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :orders do
    resources :order_items, only: [:new, :create]
    resources :images, only: [:new, :create]
    resources :notes, only: [:new, :create]
    resources :receivings, only: [:new, :create]
    resources :payments, only: [:new, :create]
    resources :repairs, only: [:new, :create]
    resources :shippings, only: [:new, :create] do
      member do
        get "resend"
      end
    end
  end
  resources :order_items, only: :destroy
  resources :shippings, only: [:edit, :update]
  resources :open_calls do
    resources :orders, only: :new
  end
  resources :user_onlines, only: [:create, :destroy]
  namespace :packing_slip do
    resources :orders, only: :show
  end
  get "orders/:order_id/shippings", to: "shippings#create_bnp", as: :create_bnp

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :product
  belongs_to :user
  has_many :notes
  has_many :repairs
  has_many :receivings
  has_many :shippings
  has_many :payments
  has_many :images
  has_many :order_items, dependent: :destroy
  has_many :repair_rates, through: :order_items
  monetize :amount_cents
  monetize :paid_cents
  accepts_nested_attributes_for :images, allow_destroy: :destroy
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :address, presence: true, length: { in: 0..60 }
  validates :address2, length: { in: 0..60 }, allow_blank: true
  validates :city, presence: true
  validates :state, presence: true
  validates :case_no, presence: true
  validates :zip, presence: true, length: { is: 5, message: "format for US: 90501" }
  validates :serial_number, presence: true, length: { is: 9, message: "format J123456789" }
  validates :telephone_no, presence: true, format: { with: /^[0-9]{10}$/, multiline: true,
    message: "format 5555555555" }
  validates :symptom, presence: true, length: { in: 10..250 }
  validates :order_status, inclusion: { in: ["Order Created", "Order Cancelled", "Item received", "Item in repair", "Completed, Shipped", "Completed, Disposed"] }
  before_create :check_order_id

  private

  def check_order_id
    orders = Order.all
    orders.empty? ? self.order_no : self.order_no = Order.last.order_no + 1
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  skip_before_action :authenticate_user!, only: [:create, :show, :new]
  before_action :order_id_find, only: [:show, :edit, :update, :destroy]

  def index
    @orders = policy_scope(Order).all
  end

  def show
    @note = Note.new
    @repair = Repair.new
    @uploader = ImageUploader.new
    authorize @order
  end

  def new
    if opencall_id_find.nil?
      @order = Order.new
      @product_model = Product.order(:model_no)
    else
      @opencall = opencall_id_find
      @order = Order.new(case_no: @opencall.case_no, first_name: @opencall.first_name, last_name: @opencall.last_name, product: @opencall.product, serial_number: @opencall.serial_number, symptom: @opencall.symptom, address: @opencall.address, address2: @opencall.address2, city: @opencall.city, state: @opencall.state, zip: @opencall.zip, telephone_no: @opencall.telephone_no, email: @opencall.email)
      @product_model = Product.order(:model_no)
    end
    authorize @order
  end

  def create
    @product_model = Product.order(:model_no)
    @order = Order.new(order_params)
    @order.user = current_user
    @notes = Note.new
    @notes.comment = "Created order request"
    @notes.user = user_signed_in? ? current_user : User.find_by_id(2)
    @order.order_status = "Order Created"
    authorize @order
    if @order.save
      if current_user.admin?
      @user = UserOnline.find_by(user: current_user)
      @user.status = "Available"
      @user.save
    end
      @notes.order = @order
      @notes.save
      redirect_to order_path(@order)
    else
      render :new
    end
  end

  def edit
    @product_model = Product.order(:model_no)
    @note = Note.new
    authorize @order
  end

  def update
    @product_model = Product.order(:model_no)
    authorize @order
    @order.update(order_params)
    redirect_to order_path(@order)
  end

  private

  def order_id_find
    @order = Order.find(params[:id])
  end

  def opencall_id_find
    if params[:open_call_id].nil?
    else
      @opencall = OpenCall.find(params[:open_call_id])
    end
  end

  def order_params
    params.require(:order).permit(:first_name, :case_no, :last_name, :address, :address2, :city, :state, :zip, :telephone_no, :email, :product_id, :serial_number, :symptom, :order_status, :notes)
  end

end

app/controllers/packing_slip/orders_controller.rb
module PackingSlip
  class OrdersController < ApplicationController

    def show
      authorize @order
      @order = Order.find(params[:id])
      respond_to do |format|
            format.html
            format.pdf do
                render pdf: "Invoice No. #{@order.id}",
                page_size: 'A4',
                template: "packing_slip/orders/show.html.erb",
                layout: "pdf.html",
                orientation: "Landscape",
                lowquality: true,
                zoom: 1,
                dpi: 75
        end
      end
    end
  end
end

app/views/orders/_form.html.erb
<% title "Create an order" %>
<div class="container">
  <div class="row justify-content-center">
  <div class="orderform-view">
    <%= simple_form_for @order do |f| %>
      <h1>Create an order</h1>
      <div class="form-row">
        <div class="col-sm">
          <%= f.input :case_no %>
        </div>
        <div class="col-sm">
          <%= f.association :product, label: "Model number", prompt: "Choose a product", collection: @product_model %>
        </div>
        <div class="col-sm">
          <%= f.input :serial_number %>
        </div>
    </div>
    <div class="form-row">
      <div class="col">
          <%= f.input :symptom %>
      </div>
    </div>
    <div class="form-row">
      <div class="col-sm">
        <%= f.input :first_name %>
      </div>
      <div class="col-sm">
        <%= f.input :last_name %>
      </div>
    </div>
      <%= f.input :address %>
      <%= f.input :address2 %>
      <div class="form-row">
        <div class="col-sm">
          <%= f.input :city %>
        </div>
        <div class="col-sm">
          <%= f.input :state, collection: [['Alabama', 'AL'],
              ['Alaska', 'AK'],
              ['Arizona', 'AZ'],
              ['Arkansas', 'AR'],
              ['California', 'CA'],
              ['Colorado', 'CO'],
              ['Connecticut', 'CT'],
              ['Delaware', 'DE'],
              ['District of Columbia', 'DC'],
              ['Florida', 'FL'],
              ['Georgia', 'GA'],
              ['Hawaii', 'HI'],
              ['Idaho', 'ID'],
              ['Illinois', 'IL'],
              ['Indiana', 'IN'],
              ['Iowa', 'IA'],
              ['Kansas', 'KS'],
              ['Kentucky', 'KY'],
              ['Louisiana', 'LA'],
              ['Maine', 'ME'],
              ['Maryland', 'MD'],
              ['Massachusetts', 'MA'],
              ['Michigan', 'MI'],
              ['Minnesota', 'MN'],
              ['Mississippi', 'MS'],
              ['Missouri', 'MO'],
              ['Montana', 'MT'],
              ['Nebraska', 'NE'],
              ['Nevada', 'NV'],
              ['New Hampshire', 'NH'],
              ['New Jersey', 'NJ'],
              ['New Mexico', 'NM'],
              ['New York', 'NY'],
              ['North Carolina', 'NC'],
              ['North Dakota', 'ND'],
              ['Ohio', 'OH'],
              ['Oklahoma', 'OK'],
              ['Oregon', 'OR'],
              ['Pennsylvania', 'PA'],
              ['Puerto Rico', 'PR'],
              ['Rhode Island', 'RI'],
              ['South Carolina', 'SC'],
              ['South Dakota', 'SD'],
              ['Tennessee', 'TN'],
              ['Texas', 'TX'],
              ['Utah', 'UT'],
              ['Vermont', 'VT'],
              ['Virginia', 'VA'],
              ['Washington', 'WA'],
              ['West Virginia', 'WV'],
              ['Wisconsin', 'WI'],
              ['Wyoming', 'WY']],
              prompt: "Select state" %>
        </div>
        <div class="col-sm">
          <%= f.input :zip %>
        </div>
      </div>
      <div class="form-row">
        <div class="col">
          <%= f.input :telephone_no %>
        </div>
        <div class="col">
          <%= f.input :email %>
        </div>
      </div>
      <%= f.submit "Submit", class: "btn btn-primary" %>
    <% end %>
  </div>
  </div>
</div>

app/views/orders/edit.html.erb
<% title "Update order" %>
<div class="container">
  <div class="row justify-content-center">
  <div class="orderform-view">
    <%= simple_form_for @order do |f| %>
      <h1>Update order</h1>
      <div class="form-row">
        <div class="col-sm">
          <%= f.input :case_no %>
        </div>
        <div class="col-sm">
          <%= f.association :product, label: "Model number", prompt: "Choose a product", collection: @product_model %>
        </div>
        <div class="col-sm">
          <%= f.input :serial_number %>
        </div>
    </div>
    <div class="form-row">
      <div class="col">
          <%= f.input :symptom %>
      </div>
    </div>
    <div class="form-row">
      <div class="col-sm">
        <%= f.input :first_name %>
      </div>
      <div class="col-sm">
        <%= f.input :last_name %>
      </div>
    </div>
      <%= f.input :address %>
      <%= f.input :address2 %>
      <div class="form-row">
        <div class="col-sm">
          <%= f.input :city %>
        </div>
        <div class="col-sm">
          <%= f.input :state, collection: [['Alabama', 'AL'],
              ['Alaska', 'AK'],
              ['Arizona', 'AZ'],
              ['Arkansas', 'AR'],
              ['California', 'CA'],
              ['Colorado', 'CO'],
              ['Connecticut', 'CT'],
              ['Delaware', 'DE'],
              ['District of Columbia', 'DC'],
              ['Florida', 'FL'],
              ['Georgia', 'GA'],
              ['Hawaii', 'HI'],
              ['Idaho', 'ID'],
              ['Illinois', 'IL'],
              ['Indiana', 'IN'],
              ['Iowa', 'IA'],
              ['Kansas', 'KS'],
              ['Kentucky', 'KY'],
              ['Louisiana', 'LA'],
              ['Maine', 'ME'],
              ['Maryland', 'MD'],
              ['Massachusetts', 'MA'],
              ['Michigan', 'MI'],
              ['Minnesota', 'MN'],
              ['Mississippi', 'MS'],
              ['Missouri', 'MO'],
              ['Montana', 'MT'],
              ['Nebraska', 'NE'],
              ['Nevada', 'NV'],
              ['New Hampshire', 'NH'],
              ['New Jersey', 'NJ'],
              ['New Mexico', 'NM'],
              ['New York', 'NY'],
              ['North Carolina', 'NC'],
              ['North Dakota', 'ND'],
              ['Ohio', 'OH'],
              ['Oklahoma', 'OK'],
              ['Oregon', 'OR'],
              ['Pennsylvania', 'PA'],
              ['Puerto Rico', 'PR'],
              ['Rhode Island', 'RI'],
              ['South Carolina', 'SC'],
              ['South Dakota', 'SD'],
              ['Tennessee', 'TN'],
              ['Texas', 'TX'],
              ['Utah', 'UT'],
              ['Vermont', 'VT'],
              ['Virginia', 'VA'],
              ['Washington', 'WA'],
              ['West Virginia', 'WV'],
              ['Wisconsin', 'WI'],
              ['Wyoming', 'WY']],
              prompt: "Select state" %>
        </div>
        <div class="col-sm">
          <%= f.input :zip %>
        </div>
      </div>
      <div class="form-row">
        <div class="col">
          <%= f.input :telephone_no %>
        </div>
        <div class="col">
          <%= f.input :email %>
        </div>

      </div>
      <%= f.submit "Submit", class: "btn btn-primary" %>
    <% end %>
  </div>
  </div>
</div>

app/views/orders/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-lg-12 col-md-6 col-sm-4">
      <h1>Orders</h1>
      <table id="orders" class="table table-striped table-bordered" style="width:100%">
        <thead>
          <tr>
            <th>Order No</th>
            <th>Case No</th>
            <th>Model</th>
            <th>Order Status</th>
            <th>State</th>
            <th>Option</th>
          </tr>
        </thead>
        <tbody>
          <% @orders.each do |order| %>
            <tr>
              <td><%= order.order_no %></td>
              <td><%= order.case_no %></td>
              <td><%= order.product.model_no %></td>
              <td><%= order.order_status %></td>
              <td><%= order.state %></td>
              <td><%= link_to(order_path(order), class: "badge badge-primary" ) do %>
                Open
              </td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/orders/new.html.erb
<%= render 'form', order: @order  %>

app/views/orders/show.html.erb
<% title "#{@order.order_no} Repair"%>
<div class="container-fluid">
  <div class="row justify-content-md-center">
    <nav class="col-md-2 offline">
      <ul class="nav flex-column">
        <strong><h4 class="text-center list-group-item active">Controls</h4></strong>
        <li class="nav-item">
          <% if policy(@order).update? %>
            <%= link_to edit_order_path(@order), class:"nav-link-order" do %>
            <i class="fas fa-folder-plus"> Update Order</i>
          <% end %>
        </li>
        <li class="nav-item">
          <% if @order.bap_ship == true %>
            <%= link_to create_bnp_path(@order), class: "nav-link-order",
                  data: { confirm: "Are you sure?" } do %>
                <i class="fas fa-box-open">Print Box Labels</i>

              <% end %>
            <% end %>
          <% end %>
        </li>
        <li class="nav-item">
          <% if policy(Payment).create? %>
              <%= link_to new_order_payment_path(@order), id: "payment-id", class:"nav-link-order" do %>
                <i class="fas fa-shopping-cart"> Charge Payment<span class="badge badge-light"><%= humanized_money_with_symbol(@order.amount - @order.paid) %></span></i>
              <% end %>
          <% end %>
        </li>
        <li class="nav-item">
          <a type="button" class="nav-link-order" onclick="printJS('<%= packing_slip_order_path(@order, format: :pdf) %>')"> <i class="fas fa-folder-open"> Print Slip</i></a>
        </li>
        <li class="nav-item">
          <% if policy(OrderItem).create? %>
            <%= link_to new_order_order_item_path(@order), class:"nav-link-order" do %>
              <i class="fas fa-cart-plus"> Add Order</i>
            <% end %>
          <% end %>
        </li>
        <li class="nav-item">
          <% if policy(Image).create? %>
            <%= link_to new_order_image_path(@order), class: "nav-link-order" do %>
              <i class="fas fa-images"> Add Photos</i>
            <% end %>
          <% end %>
        </li>
        <% if @order.receivings.empty? %>
          <li class="nav-item">
            <% if policy(Receiving).create? %>
              <%= link_to new_order_receiving_path(@order), class:"nav-link-order" do %>
              <i class="fas fa-shipping-fast"> Receive Product</i>
            <% end %>
          <% end %>
        </li>
        <% else %>
          <% if @order.order_status == "Completed, Shipped" || @order.order_status == "Completed, Disposed" %>
          <% else %>
            <li class="nav-item">
              <% if policy(Repair).create? %>
                <a id="repair_btn" type="button" data-toggle="modal" class="nav-link-order" data-target="#repairModal"><i class="fas fa-tools"> Repair Update</a></i>
              <% end %>
            </li>
          <% end %>
        <% end %>
        <li class="nav-item">
          <a type="button" class="nav-link-order" data-toggle="modal" data-target="#notesModal"><i class="fas fa-sticky-note"> Add Comment</a></i>
        </li>
      </ul>
    </nav>
    <div class="col show-page-order">
      <h1>Order No. <%= @order.order_no %> - <%= @order.order_status %></h1>
      <div class="row">
        <div class="col order-details">
          <h4>Order Reference</h4>
          <ul class="list-group">
            <li class="list-group-item">Case No.<%= @order.case_no %></li>
            <li class="list-group-item">Name <%= @order.first_name %> <%= @order.last_name %></li>
            <li class="list-group-item">Address <%= @order.address %> <%= @order.address2 %> <%= @order.city %> <%= @order.state %> <%= @order.zip %>
            </li>
            <li class="list-group-item">Contact No. <%= @order.telephone_no %></li>
            <li class="list-group-item">Email <a href="mailto:<%= @order.email %>?subject=Funai Repair Order No. <%= @order.order_no %>-<%= @order.product.model_no %>">e-mail</a></li>
          </ul>
        </div>
        <div class="col order-details">
          <h4>Product</h4>
          <ul class="list-group">
            <li class="list-group-item">Created On <%= @order.created_at.strftime("%b %d, %Y") %></li>
            <li class="list-group-item">Model No <%= @order.product.model_no %></li>
            <li class="list-group-item">Serial No <%= @order.serial_number %></li>
            <li class="list-group-item">Symptom <%= @order.symptom %></li>
            <% if @order.receivings.empty? %>
            <li class="list-group-item">Received not yet</li>
            <% else %>
              <% @order.receivings.each do |receive| %>
                <li class="list-group-item">Received <%= receive.model_no %> <%= receive.serial_number %></li>
              <% end %>
            <% end %>
          </ul>
        </div>
        <div class="col order-details">
          <h4>Order Total</h4>
          <ul class="list-group p-2">
            <li class="list-group-item">
              Total:<%= humanized_money_with_symbol(@order.amount) %>
            </li>
            <li class="list-group-item">
              Paid: <%= humanized_money_with_symbol(@order.paid) %>
            </li>
            <li class="list-group-item">
              Pending: <%= humanized_money_with_symbol(@order.amount - @order.paid) %>
            </li>
          </ul>
        </div>
      </div>
      <div class="row">
        <div class="col-md-auto order-details">
          <h4>Order Details</h4>
          <div class="col">
            <% if @order.order_items.empty? %>
              <i class="fas fa-cart-arrow-down">Empty</i>
            <% else %>
              <ul class="list-group">
                <% @order.order_items.each do |repair| %>
                <li class="list-group-item"><%= repair.repair_rate.name %>-<%= humanized_money_with_symbol(repair.repair_rate.price) %>
                  <% if policy(OrderItem).destroy? %>
                    <%= link_to order_item_path(repair),
                      method: :delete,
                      data: { confirm: "Are you sure?" } do %>
                        <i class="fas fa-trash" style="margin-left: 12px;"></i>
                      <% end %>
                  <% end %>
                </li>
                <% end %>
              </ul>
            <% end %>
          </div>
        </div>
        <div class="col-md-auto order-details">
          <h4>Shipping</h4>
            <% if @order.shippings.empty? %>
              <i class="fas fa-shipping-fast">Empty</i>
            <% else %>
            <ul class="list-group">
              <% @order.shippings.each do |item| %>
                <li class="list-group-item">
                  <%= item.name %> - <%= item.ready_ship == false ? "Awaiting on Payment" : link_to(item.shipout_tracking, "https://www.fedex.com/apps/fedextrack/?tracknumbers=#{item.shipout_tracking}&language=en&cntry_code=us", target: "_blank") %>
                  <% if item.label.nil? %>
                  <% else %>
                     <button class="btn btn-secondary btn-sm float-right" style="margin-left: 3px;" type="button" onclick="printJS('<%= root_path + item.label %>')">
                        <i class="fas fa-file-pdf"> Print</i>
                     </button>
                   <% end %>
                   <% if policy(Shipping).resend? %>
                    <% if item.name == "Return Label Fee" %>
                      <% if item.ready_ship == false %>
                      <% else %>
                        <%= link_to(resend_order_shipping_path(@order, item), data: { confirm: "Are you sure?" }, class: "btn btn-secondary btn-sm") do %>
                          <i class="fas fa-paper-plane"> Resend</i>
                        <% end %>
                      <% end %>
                    <% end %>
                  <% end %>
                </li>
              <% end %>
            <% end %>
          </ul>
        </div>
        <div class="col-md-auto order-details">
          <h4>Photos</h4>
          <% if @order.images.blank? %>
            <i class="far fa-images">Empty</i>
          <% else %>
            <% @order.images.each do |item| %>
              <%= link_to item.image.url do %>
                <%= image_tag(item.image.url, class: "img-thumbnail sm-preview") %>
              <% end %>
            <% end %>
          <% end %>
        </div>
        <% if @order.repairs.empty? %>
        <% else %>
        <div class="col-md-auto order-details">
          <h4>Repair Notes</h4>
          <ul>
            <% @order.repairs.each do |repair| %>
              <li>
                <%= repair.status %>
                <%= repair.comment %>
              </li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="col-md-auto order-details">
        <h4>Notes</h4>
        <ul>
         <% @order.notes.each do |note| %>
            <li>
            <%= User.find_by_id(note.user_id).first_name %>
            <%= note.created_at.strftime("%b %d, %Y") %>
            </li> <%= note.comment %>
          <% end %>
        </ul>
    </div>
  </div>
</div>

<!-- Modal Notes -->
<div class="modal fade" id="notesModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Add Note</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= simple_form_for [@order, @note] do |f| %>
          <%= f.input :comment %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <%= f.submit "Save change", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<!-- Order Status -->
<div class="modal fade" id="orderModal" tabindex="-1" role="dialog" aria-labelledby="orderModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="orderModalLabel">Add Note</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= simple_form_for(@order, as: :order, url: order_path(@order), method: :PUT) do |f| %>
          <%= f.input :order_status, collection: ["Order Created", "Order Cancelled", "Item received", "Item in repair", "Completed, Shipped"], prompt: "Select Status" %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <%= f.submit "Save change", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<!-- Repair Notes -->
<div class="modal fade" id="repairModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Repair Section</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" id="repair_modal">
        <%= simple_form_for [@order, @repair] do |f| %>
          <%= f.select :status, [ "Diagnosed", "Reviewed", "Dispose", "Repair Completed"] %>
          <%= f.input :comment %>
           <%= simple_fields_for :no_model_fields do |n| %>
            <%= n.input :repair_charge, collection: ["Major", "Minor", "Non-repairable"], prompt: "Select Status" %>
          <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <%= f.submit "Save change", class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>