config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: [:registrations, :passwords], controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations'
      }
  root 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :orders do
    resources :order_items, only: [:new, :create]
    resources :images, only: [:new, :create]
    resources :notes, only: [:new, :create]
    resources :receivings, only: [:new, :create]
    resources :payments, only: [:new, :create]
    resources :repairs, only: [:new, :create]
    resources :shippings, only: [:new, :create] do
      member do
        get "resend"
      end
    end
  end
  resources :order_items, only: :destroy
  resources :shippings, only: [:edit, :update]
  resources :open_calls do
    resources :orders, only: :new
  end
  resources :user_onlines, only: [:create, :destroy]
  namespace :packing_slip do
    resources :orders, only: :show
  end
  get "orders/:order_id/shippings", to: "shippings#create_bnp", as: :create_bnp

end

app/views/pages/home.html.erb
<div class="container-fluid">
  <div class="row" style="margin-top: 15px;">
    <div class="col-sm text-center">
      <span class="list-group-item active">Callbacks</span>
      <ul>
        <li>
          <h1><span class="badge badge-secondary">Count: <%= OpenCall.pending_calls_count %></span></h1>
        </li>
      </ul>
    </div>
    <div class="col-sm text-center">
      <span class="list-group-item active">Box and Packing Shipping</span>
      <ul style="margin-top: 10px;">
        <% @pending_shipping.each do |ship|  %>
          <li><%= ship.product.model_no %> - <%= link_to "Open Order", order_path(ship), class: "btn btn-warning" %> <%= ship.order_no %></li>
        <% end %>
     </ul>
    </div>
    <div class="col-sm text-center">
      <span class="list-group-item active">Today Sales</span>
     <ul>
       <li>
        <h1><span class="badge badge-secondary">$ <%= Payment.today_sales %></span></h1>
       </li>
     </ul>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-6" id="columnchart_material" style="width: 800px; height: 500px;">
    </div>
    <div class="col-sm-6">
      <h4>Links</h4>
      <p>Coming soon for reporting</p>
    </div>
  </div>
</div>

<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
  <script type="text/javascript">
      google.charts.load('current', {'packages':['bar']});
      google.charts.setOnLoadCallback(drawChart);

      function drawChart() {
        var data = JSON.parse('<%= Payment.sales_vs_profit.to_json.html_safe  %>');
        data = [['', 'Sales', 'Expenses', 'Profit']].concat(data);
        data = google.visualization.arrayToDataTable(data);

        var options = {
          chart: {
            title: '30-day Performance',
            subtitle: 'Sales, Expenses, and Profit',
          }
        };

        var chart = new google.charts.Bar(document.getElementById('columnchart_material'));

        chart.draw(data, google.charts.Bar.convertOptions(options));
      }
</script>