config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: [:registrations, :passwords], controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations'
      }
  root 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :orders do
    resources :order_items, only: [:new, :create]
    resources :images, only: [:new, :create]
    resources :notes, only: [:new, :create]
    resources :receivings, only: [:new, :create]
    resources :payments, only: [:new, :create]
    resources :repairs, only: [:new, :create]
    resources :shippings, only: [:new, :create] do
      member do
        get "resend"
      end
    end
  end
  resources :order_items, only: :destroy
  resources :shippings, only: [:edit, :update]
  resources :open_calls do
    resources :orders, only: :new
  end
  resources :user_onlines, only: [:create, :destroy]
  namespace :packing_slip do
    resources :orders, only: :show
  end
  get "orders/:order_id/shippings", to: "shippings#create_bnp", as: :create_bnp

end

app/models/open_call.rb
class OpenCall < ApplicationRecord
  belongs_to :product
  belongs_to :user
  validates :case_no, presence: true
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :address, presence: true, length: { in: 0..60 }
  validates :address2, length: { in: 0..60 }, allow_blank: true
  validates :city, presence: true
  validates :state, presence: true
  validates :zip, presence: true
  validates :telephone_no, presence: true, format: { with: /^[0-9]{10}$/, multiline: true,
    message: "format 5555555555" }
  validates :symptom, presence: true, length: { in: 10..250 }
  validates :status, presence: true
  validates :serial_number, presence: true, length: { in: 9..14 }
  validates :email, presence: true, format: { with: Devise.email_regexp, message: "invalid email" }
  geocoded_by :address_item
  after_validation :geocode

  def address_item
    [address, city, state, zip, "USA"].compact.join(', ')
  end

  def self.pending_calls_count
    @calls = self.where(status: ["Open Call", "Left Message"])
    return @calls.count
  end
end

app/controllers/open_calls_controller.rb
class OpenCallsController < ApplicationController
  before_action :call_id_find, only: [:show, :edit, :update, :destroy]

  def index
    @opencalls = policy_scope(OpenCall).where.not(status: ["Canceled", "Create Order"])
  end

  def new
    @opencall = OpenCall.new
    @product_model = Product.order(:model_no)
    authorize @opencall
  end

  def create
    @opencall = OpenCall.new(open_params)
    @opencall.user = current_user
    @product_model = Product.order(:model_no)
    authorize @opencall
    if @opencall.save
      mail = OrderMailer.with(call: @opencall).create_call
      Shipping.shipping_address(@opencall)
      mail.deliver_now
      redirect_to open_calls_path
    else
      render :new
    end
  end

  def show
    authorize @opencall
    @markers = [{
          lat: @opencall.latitude,
          lng: @opencall.longitude
        }]
  end

  def edit
    authorize @opencall
    @product_model = Product.order(:model_no)
    if current_user.admin?
      @user = UserOnline.find_by(user: current_user)
      if @user.nil?
        @user = UserOnline.create(active: true, status: "In a call", user: current_user)
      else
        @user.status = "In a Call"
        @user.save
      end
    end
  end

  def update
    authorize @opencall
    @opencall.update(open_params)
    if @opencall.status == "Create Order"
      if current_user.admin?
        @user = UserOnline.find_by(user: current_user)
        @user.status = "In a Order"
        @user.user = current_user
        @user.save
      end
      redirect_to new_open_call_order_path(@opencall)
    else
      if current_user.admin?
        @user = UserOnline.find_by(user: current_user)
        @user.status = "Available"
        @user.user = current_user
        @user.save
      end
      redirect_to open_calls_path
    end
  end

  def call_id_find
    @opencall = OpenCall.find(params[:id])
  end

  def open_params
    params.require(:open_call).permit(:first_name, :case_no, :last_name, :address, :address2, :city, :state, :zip, :telephone_no, :email, :product_id, :serial_number, :symptom, :status)
  end
end

app/views/open_calls/_opencallform.html.erb
<div class="container">
  <div class="row justify-content-center">
  <div class="orderform-view">
    <%= simple_form_for @opencall do |f| %>
      <h1>Callback</h1>
      <div class="form-row">
        <div class="col-sm">
          <%= f.input :case_no %>
        </div>
        <div class="col-sm">
          <%= f.association :product, label: "Model number", prompt: "Choose a product", collection: @product_model %>
        </div>
        <div class="col-sm">
          <%= f.input :serial_number %>
        </div>
    </div>
    <div class="form-row">
      <div class="col">
          <%= f.input :symptom %>
      </div>
    </div>
    <div class="form-row">
      <div class="col-sm">
        <%= f.input :first_name %>
      </div>
      <div class="col-sm">
        <%= f.input :last_name %>
      </div>
    </div>
      <%= f.input :address %>
      <%= f.input :address2 %>
      <div class="form-row">
        <div class="col-sm">
          <%= f.input :city %>
        </div>
        <div class="col-sm">
          <%= f.input :state, collection: [['Alabama', 'AL'],
              ['Alaska', 'AK'],
              ['Arizona', 'AZ'],
              ['Arkansas', 'AR'],
              ['California', 'CA'],
              ['Colorado', 'CO'],
              ['Connecticut', 'CT'],
              ['Delaware', 'DE'],
              ['District of Columbia', 'DC'],
              ['Florida', 'FL'],
              ['Georgia', 'GA'],
              ['Hawaii', 'HI'],
              ['Idaho', 'ID'],
              ['Illinois', 'IL'],
              ['Indiana', 'IN'],
              ['Iowa', 'IA'],
              ['Kansas', 'KS'],
              ['Kentucky', 'KY'],
              ['Louisiana', 'LA'],
              ['Maine', 'ME'],
              ['Maryland', 'MD'],
              ['Massachusetts', 'MA'],
              ['Michigan', 'MI'],
              ['Minnesota', 'MN'],
              ['Mississippi', 'MS'],
              ['Missouri', 'MO'],
              ['Montana', 'MT'],
              ['Nebraska', 'NE'],
              ['Nevada', 'NV'],
              ['New Hampshire', 'NH'],
              ['New Jersey', 'NJ'],
              ['New Mexico', 'NM'],
              ['New York', 'NY'],
              ['North Carolina', 'NC'],
              ['North Dakota', 'ND'],
              ['Ohio', 'OH'],
              ['Oklahoma', 'OK'],
              ['Oregon', 'OR'],
              ['Pennsylvania', 'PA'],
              ['Puerto Rico', 'PR'],
              ['Rhode Island', 'RI'],
              ['South Carolina', 'SC'],
              ['South Dakota', 'SD'],
              ['Tennessee', 'TN'],
              ['Texas', 'TX'],
              ['Utah', 'UT'],
              ['Vermont', 'VT'],
              ['Virginia', 'VA'],
              ['Washington', 'WA'],
              ['West Virginia', 'WV'],
              ['Wisconsin', 'WI'],
              ['Wyoming', 'WY']],
              prompt: "Select state" %>
        </div>
        <div class="col-sm">
          <%= f.input :zip %>
        </div>
      </div>
      <div class="form-row">
        <div class="col">
          <%= f.input :telephone_no %>
        </div>
        <div class="col">
          <%= f.input :email %>
        </div>
        <div class="col">
          <%= f.input :status, collection: ["Open Call", "Left Message", "Create Order", "Canceled"] %>
        </div>
      </div>
      <%= f.submit "Submit", class: "btn btn-primary" %>
    <% end %>
  </div>
  </div>
</div>

app/views/open_calls/edit.html.erb
<div class="container">
  <div class="row justify-content-center">
  <div class="orderform-view">
    <%= simple_form_for @opencall do |f| %>
      <h1>Callback</h1>
      <div class="form-row">
        <div class="col-sm">
          <%= f.input :case_no %>
        </div>
        <div class="col-sm">
          <%= f.association :product, label: "Model number", prompt: "Choose a product", collection: @product_model %>
        </div>
        <div class="col-sm">
          <%= f.input :serial_number %>
        </div>
    </div>
    <div class="form-row">
      <div class="col">
          <%= f.input :symptom %>
      </div>
    </div>
    <div class="form-row">
      <div class="col-sm">
        <%= f.input :first_name %>
      </div>
      <div class="col-sm">
        <%= f.input :last_name %>
      </div>
      <div class="col">
        <%= f.input :status, collection: ["Open Call", "Left Message", "Create Order", "Canceled"] %>
      </div>
    </div>
      <%= f.submit "Submit", class: "btn btn-primary" %>
    <% end %>
    </div>
  </div>
</div>

app/views/open_calls/index.html.erb
<div class="container-fluid">
  <div class="row">
    <nav class="col-md-2 offline">
      <h3>Online (Ohio)</h3>
      <% if UserOnline.my_online_users.empty? %>
        <span class="offline-text">Offline-Setup an Open Call and we will callback later.</span>
      <% else %>
        <% UserOnline.my_online_users.each do |user| %>
          <i class="fas fa-user-alt"></i> <%= user.user.first_name %> - <%= user.status %>-EXT: 119
        <% end %>
      <% end %>
      <% if policy(OpenCall).create? %>
        <%= link_to "Create Call", new_open_call_path, class: "btn btn-primary btn-sm" %>
      <% end %>
    </nav>
    <div class="col-10">
      <h1>Callbacks</h1>
      <table id="calls" class="table table-striped table-bordered" style="width: 100%;height: 250px;">
        <thead>
          <tr>
            <th>Case No</th>
            <th>First Name</th>
            <th>Last Name</th>
            <th>State</th>
            <th>Model No</th>
            <th>Status</th>
            <th>Option</th>
          </tr>
        </thead>
        <tbody>
          <% @opencalls.each do |call| %>
            <tr>
              <td><%= call.case_no %></td>
              <td><%= call.first_name %></td>
              <td><%= call.last_name %></td>
              <td><%= call.state %></td>
              <td><%= call.product.model_no %></td>
              <td><%= call.status %></td>
              <td><%= link_to(open_call_path(call), class: "badge badge-primary" ) do %>
                Open
              </td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/open_calls/new.html.erb
<%= render "opencallform" %>

app/views/open_calls/show.html.erb
<% title "Open Call #{@opencall.id}" %>
<div class="conainter">
  <div class="row" style="margin: 0;">
    <div class="button-control col-sm">
      <div class="btn-group" role="group" aria-label="Button group with nested dropdown">
        <div class="btn-group" role="group">
          <button id="btnGroupDrop1" type="button" class="btn btn-secondary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Controls
          </button>
          <div class="dropdown-menu" aria-labelledby="btnGroupDrop1">
            <% if policy(OpenCall).edit? %>
              <%= link_to "Update", edit_open_call_path(@opencall), class: "dropdown-item" %>
           <% end %>
            <%= link_to "Back Open Calls", open_calls_path, class: "dropdown-item" %>
          </div>
        </div>
      </div>
    </div>
    <div class="timezones col-sm">
      <iframe src="http://free.timeanddate.com/clock/i6u2j3p4/n179/fn7/fs20/tct/pct/ftb/th2/ta1" frameborder="0" width="179" height="30" allowTransparency="true"></iframe>
      <iframe src="http://free.timeanddate.com/clock/i6u2j3p4/n64/fn7/fs20/tct/pct/ftb/th2/ta1" frameborder="0" width="179" height="30" allowTransparency="true"></iframe>
      <iframe src="http://free.timeanddate.com/clock/i6u2j3p4/n137/fn7/fs20/tct/pct/ftb/th2/ta1" frameborder="0" width="177" height="30" allowTransparency="true"></iframe>
    </div>
  </div>
  <div class="row" style="margin: 0;">
    <div class="col-md-auto col-lg-4">
      <h2 class="text-center">Open Status</h2>
    <ul class="text-left">
      <li><i class="fas fa-calendar-alt"></i> Created On: <%= @opencall.created_at.strftime("%b %d, %Y") %></li>
      <li><i class="fas fa-clipboard-check"></i> Status: <%= @opencall.status %></li>
      <li><i class="fas fa-phone"></i> Phone: <%= @opencall.telephone_no %></li>
      <li><i class="fas fa-envelope-open-text"></i> Email:
        <% if @opencall.email.empty? %>
        <% else %>
          <a href="mailto:<%= @opencall.email %>?subject=Funai Pending Repair-<%= @opencall.product.model_no %>"><%= @opencall.email %></a>
        <% end %>
      </li>
    </ul>
    </div>
    <div class="col-md-auto col-lg-4">
      <h2 class="text-center">Open Callback</h2>
      <ul class="text-left">
        <li><i class="fas fa-user-secret"></i> Customer: <%= @opencall.first_name %> <%= @opencall.last_name %></li>
        <li><i class="fas fa-box"></i> Model No.: <%= @opencall.product.model_no %></li>
        <li><i class="fas fa-file-alt"></i> Symptom: <%= @opencall.symptom %></li>
      </ul>
    </div>
    <div class="col-md-auto col-lg-4">
      <h2 class="text-center">FedEx Validate</h2>
      <ul class="text-left fedex-item">
          <li>Rating: <%= Shipping.shipping_address(@opencall).score %></li>
          <li>Confirmation: <%= Shipping.shipping_address(@opencall).confirmed %></li>
          <li>Type: <%= Shipping.shipping_address(@opencall).status %></li>
          <li>Address: <%= @opencall.address %> <%= @opencall.address2 %> <%= @opencall.city %> <%= @opencall.state %> <%= @opencall.zip %>
          </li>
      </ul>
    </div>
  </div>
  <div
    id="map"
    style="width: 100%;
    height: 426px;"
    data-markers="<%= @markers.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
</div>